name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ssh.itu.edu.tr
        username: apaydink19
        password: ${{ secrets.ftp_password}}
        port: 22
        script: whoami
