# This is a basic workflow to help you get started with Actions

on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ssh.itu.edu.tr
        username: apaydink19
        password: ${{ secrets.ftp_password }}
        server-dir: web.itu.edu.tr/apaydink19/public_html/
